name: "Gomoku CI"

on:
  push:

jobs:
  mirror:
    name: "Mirror to the Epitech repository"
    runs-on: "ubuntu-latest"
    if: "${{ github.ref_name == 'main' }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Mirror"
        uses: "pixta-dev/repository-mirroring-action@v1.1.1"
        with:
          target_repo_url: "${{ vars.MIRROR_URL }}"
          ssh_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
